# Generated by Django 5.2.2 on 2025-06-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0002_palette_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
