# Generated by Django 5.2.2 on 2025-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
