# Generated by Django 5.2.2 on 2025-07-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0005_alter_palette_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
