# Generated by Django 5.2.2 on 2025-07-15 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0006_alter_palette_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['time', 'id'], name='palettes_pa_time_86c014_idx'),
        ),
        migrations.AddIndex(
            model_name='palette',
            index=models.Index(fields=['-time', '-id'], name='palettes_pa_time_d209f0_idx'),
        ),
    ]
